export function GetProductsList() {
	// fake data (fetch to database then)
	const products = [
		{
			product_id: "N1",
			thumnail: "product_1_540p.png",
			type: "001",
			title: "test cai card nay",
			price: 60,
			sold: 435,
			coupon_percent: null,
			coupon_Expired: null,
			description: `<p class="m-0">This product is so amazing</p><p class="m-0">you should buy it bro</p>`,
			variants: [],
		},
		{
			product_id: "N2",
			thumnail: "product_2_540p.png",
			type: "001",
			title: "test cai card nay",
			price: 123,
			sold: 98,
			coupon_percent: 10,
			coupon_Expired: "2024-06-1",
			description: `<p class="m-0">This is description</p>`,
			variants: [],
		},
		{
			product_id: "N3",
			thumnail: "product_3_540p.png",
			type: "001",
			title: "test cai card nay",
			price: 54,
			sold: 5843,
			coupon_percent: 20,
			coupon_Expired: "2024-06-1",
			description: `<p class="m-0">This is description</p>`,
			variants: [],
		},
		{
			product_id: "N4",
			thumnail: "product_4_540p.png",
			type: "001",
			title: "test cai card nay",
			price: 87,
			sold: 5,
			coupon_percent: "20",
			coupon_Expired: "2024-06-1",
			description: `<p class="m-0">This is description</p>`,
			variants: [],
		},
		{
			product_id: "N5",
			thumnail: "product_5_540p.png",
			type: "001",
			title: "test cai card nay",
			price: 69,
			sold: 766,
			coupon_percent: null,
			coupon_Expired: null,
			description: `<p class="m-0">This is description</p>`,
			variants: [],
		},
		{
			product_id: "N6",
			thumnail: "product_6_540p.png",
			type: "001",
			title: "test cai card nay",
			price: 6500,
			sold: 12,
			coupon_percent: 30,
			coupon_Expired: null,
			description: `<p class="m-0">This is description</p>`,
			variants: [],
		},

		{
			product_id: "N7",
			thumnail: "product_7_540p.png",
			type: "001",
			title: "test cai card nay",
			price: 60,
			sold: 435,
			coupon_percent: null,
			coupon_Expired: null,
			description: `<p class="m-0">This is description</p>`,
			variants: [],
		},
		{
			product_id: "N8",
			thumnail: "product_8_540p.png",
			type: "001",
			title: "test cai card nay",
			price: 123,
			sold: 98,
			coupon_percent: 10,
			coupon_Expired: "2024-06-1",
			description: `<p class="m-0">This is description</p>`,
			variants: [],
		},
		{
			product_id: "N9",
			thumnail: "product_9_540p.png",
			type: "001",
			title: "test cai card nay",
			price: 54,
			sold: 5843,
			coupon_percent: 20,
			coupon_Expired: "2024-06-1",
			description: `<p class="m-0">This is description</p>`,
			variants: [],
		},
		{
			product_id: "N10",
			thumnail: "product_10_540p.png",
			type: "001",
			title: "test cai card nay",
			price: 87,
			sold: 5,
			coupon_percent: "20",
			coupon_Expired: "2024-06-1",
			description: `<p class="m-0">This is description</p>`,
			variants: [],
		},
		{
			product_id: "N11",
			thumnail: "product_11_540p.png",
			type: "001",
			title: "test cai card nay",
			price: 69,
			sold: 766,
			coupon_percent: null,
			coupon_Expired: null,
			description: `<p class="m-0">This is description</p>`,
			variants: [],
		},
		{
			product_id: "N12",
			thumnail: "product_12_540p.png",
			type: "001",
			title: "test cai card nay",
			price: 6500,
			sold: 12,
			coupon_percent: 30,
			coupon_Expired: null,
			description: `<p class="m-0">This is description</p>`,
			variants: [],
		},

		{
			product_id: "N13",
			thumnail: "product_13_540p.png",
			type: "001",
			title: "test cai card nay",
			price: 60,
			sold: 435,
			coupon_percent: null,
			coupon_Expired: null,
			description: `<p class="m-0">This is description</p>`,
			variants: [],
		},
		{
			product_id: "N14",
			thumnail: "product_14_540p.png",
			type: "001",
			title: "test cai card nay",
			price: 123,
			sold: 98,
			coupon_percent: 10,
			coupon_Expired: "2024-06-1",
			description: `<p class="m-0">This is description</p>`,
			variants: [],
		},
		{
			product_id: "N15",
			thumnail: "product_15_540p.png",
			type: "001",
			title: "test cai card nay",
			price: 54,
			sold: 5843,
			coupon_percent: 20,
			coupon_Expired: "2024-06-1",
			description: `<p class="m-0">This is description</p>`,
			variants: [],
		},
		{
			product_id: "N16",
			thumnail: "product_16_540p.png",
			type: "001",
			title: "test cai card nay",
			price: 87,
			sold: 5,
			coupon_percent: "20",
			coupon_Expired: "2024-06-1",
			description: `<p class="m-0">This is description</p>`,
			variants: [],
		},
		{
			product_id: "N17",
			thumnail: "product_17_540p.png",
			type: "001",
			title: "test cai card nay",
			price: 69,
			sold: 766,
			coupon_percent: null,
			coupon_Expired: null,
			description: `<p class="m-0">This is description</p>`,
			variants: [],
		},
		{
			product_id: "N18",
			thumnail: "product_18_540p.png",
			type: "001",
			title: "test cai card nay",
			price: 6500,
			sold: 12,
			coupon_percent: 30,
			coupon_Expired: null,
			description: `<p class="m-0">This is description</p>`,
			variants: [],
		},
		{
			product_id: "N19",
			thumnail: "product_19_540p.png",
			type: "001",
			title: "test cai card nay",
			price: 6500,
			sold: 12,
			coupon_percent: 30,
			coupon_Expired: null,
			description: `<p class="m-0">This is description</p>`,
			variants: [],
		},
		{
			product_id: "N20",
			thumnail: "product_20_540p.png",
			type: "001",
			title: "test cai card nay",
			price: 6500,
			sold: 12,
			coupon_percent: 30,
			coupon_Expired: null,
			description: `<p class="m-0">This is description</p>`,
			variants: [],
		},
		{
			product_id: "N21",
			thumnail: "product_21_540p.png",
			type: "001",
			title: "test cai card nay",
			price: 60,
			sold: 435,
			coupon_percent: null,
			coupon_Expired: null,
			description: `<p class="m-0">This is description</p>`,
			variants: [],
		},
		{
			product_id: "N22",
			thumnail: "product_22_540p.png",
			type: "001",
			title: "test cai card nay",
			price: 123,
			sold: 98,
			coupon_percent: 10,
			coupon_Expired: "2024-06-1",
			description: `<p class="m-0">This is description</p>`,
			variants: [],
		},
		{
			product_id: "N23",
			thumnail: "product_23_540p.png",
			type: "001",
			title: "test cai card nay",
			price: 54,
			sold: 5843,
			coupon_percent: 20,
			coupon_Expired: "2024-06-1",
			description: `<p class="m-0">This is description</p>`,
			variants: [],
		},
		{
			product_id: "N24",
			thumnail: "product_24_540p.png",
			type: "001",
			title: "test cai card nay",
			price: 87,
			sold: 5,
			coupon_percent: "20",
			coupon_Expired: "2024-06-1",
			description: `<p class="m-0">This is description</p>`,
			variants: [],
		},
		{
			product_id: "N25",
			thumnail: "product_25_540p.png",
			type: "001",
			title: "test cai card nay",
			price: 69,
			sold: 766,
			coupon_percent: null,
			coupon_Expired: null,
			description: `<p class="m-0">This is description</p>`,
			variants: [],
		},
		{
			product_id: "N26",
			thumnail: "product_26_540p.png",
			type: "001",
			title: "test cai card nay",
			price: 6500,
			sold: 12,
			coupon_percent: 30,
			coupon_Expired: null,
			description: `<p class="m-0">This is description</p>`,
			variants: [],
		},
		{
			product_id: "N27",
			thumnail: "product_27_540p.png",
			type: "001",
			title: "test cai card nay",
			price: 6500,
			sold: 12,
			coupon_percent: 30,
			coupon_Expired: null,
			description: `<p class="m-0">This is description</p>`,
			variants: [],
		},
		{
			product_id: "N28",
			thumnail: "product_28_540p.png",
			type: "001",
			title: "test cai card nay",
			price: 6500,
			sold: 12,
			coupon_percent: 30,
			coupon_Expired: null,
			description: `<p class="m-0">This is description</p>`,
			variants: [],
		},
		{
			product_id: "N29",
			thumnail: "product_29_540p.png",
			type: "001",
			title: "test cai card nay",
			price: 6500,
			sold: 12,
			coupon_percent: 30,
			coupon_Expired: null,
			description: `<p class="m-0">This is description</p>`,
			variants: [],
		},
		{
			product_id: "N30",
			thumnail: "product_30_540p.png",
			type: "001",
			title: "test cai card nay",
			price: 6500,
			sold: 12,
			coupon_percent: 30,
			coupon_Expired: null,
			description: `<p class="m-0">This is description</p>`,
			variants: [],
		},
		{
			product_id: "N31",
			thumnail: "product_31_540p.png",
			type: "001",
			title: "test cai card nay",
			price: 6500,
			sold: 12,
			coupon_percent: 30,
			coupon_Expired: null,
			description: `<p class="m-0">This is description</p>`,
			variants: [],
		},
	];
	return products;
}
